### DISCUSSION TITLE
Welcome and status

### DISCUSSION THREAD

**Discussion by bdarcus** [bdarcus/csln#43] [Announcements]
I stumbled into doing this rust implementation after experimenting with code generation from the prototype typescript and JSON schemas.

While Rust is a somewhat large mountain for me, I learned fairly quickly it has a lot of advantages, and managed to make surprisingly rapid progress on the code.

The basic draft model and core processor is complete, but there's still a lot of work to do.

**Comment by bdarcus** [comment]
For the past few weeks I've been adding features, and refactoring along the way, to lay the groundwork to implement a real world style: Chicago author-date.

I'm about ready to do that.

**Comment by bdarcus** [comment]
I've somewhat arbitrarily tagged 0.2.0, which I probably should have done awhile ago. But I've made a lot of [progress](https://github.com/bdarcus/csln/blob/main/CHANGELOG.md) since the first tag, and my time will be less in the coming months. So Chicago may have to wait. But I'm collecting some notes in #120.

A very high-level summary of where this at ATM:

- complete-ish draft models for bibliography, citations, styles, locales
- YAML and JSON serialization and deserialization of these models, and a `csln-schemas` binary that will create JSON schemas from them
- a processor which can create formatted string output using the above inputs, but which is designed for pluggable renderers (see #105); includes basic author substitution, basic EDTF date parsing and formatting, and a few other things I'm likely forgetting
- a `csln` CLI that uses the above; it's Rust, so a single binary, and very fast.

----------------

Here's what you now see from the command line.

```console
❯ target/debug/csln -s processor/examples/style.csl.yaml -b processor/examples/chicago.bib.yaml -l processor/locales/locale-en.yaml
Bissell, Tom. (2011). Extra Lives: Why Video Games Matter. Vintage Books.

Daum, Meghan ed. (2015). Selfish, Shallow, and Self-Absorbed: Sixteen Writers on the Decision Not to Have Kids. Picador.

Glass, Jennifer & Philip Levchak. (2014). Red States, Blue States, and Divorce: Understanding the Impact of Conservative Protestantism on Regional Variation in Divorce Rates. American Journal of Sociology. 119. 10.1086/674703.

Gunderson, Alex R & Manuel Leal. (2015). Patterns of Thermal Constraint on Ectotherm Activity. American Naturalist. May 1. 10.1086/680849.

Hutter, Michael. (2011). Infinite Surprises: Value in the Creative Industries. edited by Beckert, Jens & Patrick Aspers. The Worth of Goods: Valuation and Pricing in the Economy. Oxford University Press.

Lampel, Joseph, Theresa Lant, & Jamal Shamsie. (2000). Balancing Act: Learning from Organizing Practices in Cultural Industries. Organization Science. 11.

Liu, Jui-Ch’i. (2015). Beholding the Feminine Sublime: Lee Miller’s War Photography. Signs. 40. 10.1086/678242.

Meyerovitch, Eva. (1959). The Gnostic Manuscripts of Upper Egypt. Diogenes.
```

And here's the bibliography template that specifies that output:

```yaml
bibliography: 
  template:
    - contributor: author
      form: long
    - date: issued
      form: year
      rendering: # not a fan of this
        wrap: parentheses
    - title: primary
    - contributor: editor
      form: verb
    - title: parent-monograph
      prefix: In 
      emph: true
    - title: parent-serial
    - date: issued
      form: month-day
    - number: volume
    - variable: doi
    - contributor: publisher # location?
      form: long # make optional, with default?
      delimiter: colon # scope? delimiter vs item-delimiter?
```

Note: this is YAML, of course, and designed to be easily hand-editable in something like `emacs`, `neovim`, or `vscode`. But perhaps more important: think about how that might work in a GUI editor.
