### ISSUE TITLE
use pattern-matching idea rather than conditional?

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csln#104]
Don't know if this is a crazy idea, but writing it down just in case it's not.

Rather than adding a conditional to the template language, perhaps there's a way to implement an approach borrowed from the pattern-matching you see in different languages?

Like, say:

```yaml
match:
  type:
    book: ...
    article: ...
    default: ....
```
