### ISSUE TITLE
Titles

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csln#106]
As I've been experimenting (see #100), titles turn out to be deceptively tricky.

The way CSL 1.0 works, we have:

- title (the title of the cited work)
- container-title (the title of the containing parent work, periodical, etc.)

The problem is, formatting of each of those depends on their type; hence a primary reason for the conditional.

For example, it's extremely common to render component titles quoted, and otherwise render them in italics.

With #100, I now have this:

```yaml
bibliography: 
  template:
    - contributor: author
      form: long
    - date: issued
      form: year
    - title: title # QUESTION
    - title: parent-monograph # NOTE
      prefix: In 
      emph: true
    - title: parent-serial # NOTE
      emph: true
    - date: issued
      form: month-day
    - number: volume
    - variable: doi
  ```

The "note": these components only render if there's a value for them. So in effect, they are simple conditionals.

The "question": what to do with the main title?

Options:

1. add top-level config options for this, per #104, which are in effect like standardized 1.0 macros
2. split that title type into two (`monograph-title` and `component-title` probably), just like in #100 for the parent title; could easily be extended later to include additional conditions, like `type`

The first is probably more complex, the second would result in more verbose templates.

PS - I am aware of needing to think about related titles other than parents/containers; ideally they can be easily added.

**Comment by bdarcus** [comment]
If and when you have time, @denismaier, any thoughts on titles?

**Comment by denismaier** [comment]
Just a quick question for clarification: what do you mean with main title?

**Comment by bdarcus** [comment]
Yeah: I can see that's ambiguous.

The work title; CSL 1.0 "title".

**Comment by bdarcus** [comment]
Here's the original discussion thread that documents the decision to add macros.

https://sourceforge.net/p/xbiblio/mailman/xbiblio-devel/thread/D221FAB5-D1A8-47F5-98A9-E1EE825641E6%40simonster.com/#msg3519484

Still reading through it trying to figure out why we ditched the required article, book, chapter templates.

**Comment by denismaier** [comment]
Ok, a couple of ideas:

- use macros instead of rendering the title directly. In this macro, using conditionals wouldn't be to painful, or would it?

- I think the pattern matching idea could be quite nice. It's actually close to what biblatex does: https://github.com/plk/biblatex/blob/083c54d7ab9e09d254c5b0ce1b508fd10074e48c/tex/latex/biblatex/biblatex.def#L579C32-L579C32 defines the field formats for the title (first the default format, then diverging formats for special types). In styles you'll then just use `\printfield` to actually print the title using the defined format. (I think there's a way to override it if that should be necessary.)

- regarding conditionals: one way to go could be to provide `conditionals`, but also some syntactic sugar.

By the way, while we're at titles, biblatex also has a `booktitle` and a `maintitle`, so there should probably another level in the hierarchy.

**Comment by bdarcus** [comment]
The BibLaTeX examples are indeed interesting. They basically use type lists for the conditions; something like:

```yaml
- title: title
  types: [ article, post ]
```

> ... biblatex also has a booktitle and a maintitle, so there should probably another level in the hierarchy.

Would not `booktitle` basically be this `parent-monograph`?

**Comment by denismaier** [comment]
Bruce D'Arcus. An essay concerning reference lists. In Collected Works, Vol. 5: On citations and references...
Book title: volume title
Maintitle: Collected Works

**Comment by bdarcus** [comment]
I think, on reflection, the primary issue is only with primary titles.

Given my general uncertainty about what or whether we need a template conditional, my impulse is to be more minimal; something like:, at the top-level

```yaml
  titles:
    match:
    - class: component # chapter and article titles render the same
      style: [quote]
    default:
      style: [emph]
```
