### ISSUE TITLE
Add support for in-press and no date sorting config, etc

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csln#114]
Probably the cleanest is to add these options to the `SortKey` enum, so one can just do:

```yaml
sort:
  template:
    - author
    - in-press
    - no-date
    - year
```

Another option is:

```yaml
sort:
  noDate: 0
  inPress: 3000
```
