### ISSUE TITLE
Clarify display as sort config

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csln#124]
Right now, there's just a single option for this.

But need to account for substitution, and that "authors" typically display differently, because of their role in sorting.

Probably the right approach is something like:

```yaml
display_as_sort:
  default: none
  author: first
```
