### ISSUE TITLE
links

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csln#155]
Another issue in the CSL world is hyperlinks.

I think we figured out a reasonable initial solution there, which I will come back to and link later here.

Here's a related case.

https://github.com/typst/typst/discussions/4420

It might be so simple as doing something like this?

```yaml
links:
    anchor: title # to just link on the target, value could be url-or-doi
    target: url-or-doi
```

Yes, would need to consider other doi-like URLs, like for pubmed and such. But I don't see that as a problem.
