### ISSUE TITLE
Add Style conditional

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csln#20]
No particular reason I haven't implemented it yet; just need to do it.

There's still a question of whether we need to make an already complicated model more complicated, or if we can instead simplify by putting more logic into the parameter options.

**Comment by bdarcus** [comment]
Maybe could do something like this?

```yaml
title: parent-title
condition:
  - type: [article, chapter]
    match: any # default
    rendering: [quote]
  - default:
    rendering: [emph]
```
