### ISSUE TITLE
Implement full document processing

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csln#49]
My first step on rendering was a basic bibliography.

Next step is adding citations, and full document processing.

To do that, need to resolve some questions in the context of real style examples.

## Do we need the 1.0 notion of a style type? 

If yes, the default should be in-text, since that's what I use :-)

And should it be a global option, or only on `citation`?

## What about other defaults? 

There's a wide range of them in the style model we could set. Which ones should we, and what should the values be? 

Again, I'll likely privilege my own preferences, so long as it doesn't cause problems in other contexts.

## Which document format to start with?

I'd like it to be djot, but that depends on progress there.

Otherwise, maybe pandoc?

**Comment by denismaier** [comment]
> ## Do we need the 1.0 notion of a style type?
> 
> If yes, the default should be in-text, since that's what I use :-)
> 
> And should it be a global option, or only on `citation`?

I think it'd make sense to perhaps follow the biblatex approach. Define a couple of citation commands and make one the default (as in \autocite).

**Comment by denismaier** [comment]
> Which document format to start with?
> I'd like it to be djot, but that depends on progress there.
> Otherwise, maybe pandoc?

Panfoc. Because IIUC djot itself will translate a djot document to the pandoc AST. Problem with this approach is that you'll be limited by pandoc's types for citations.

**Comment by bdarcus** [comment]
There's a rust djot parser.

**Comment by bdarcus** [comment]
> I think it'd make sense to perhaps follow the biblatex approach. Define a couple of citation commands and make one the default (as in \autocite).

To come back to this ....

There's really two things here:

1. what a citation should look like in general (author-date, note, numeric)
2. locally-modified citations 

The question was about 1.

For 2, here's how I currently model this:

https://github.com/bdarcus/csln/blob/f0cff31da320b687801e558761546881fc8cea0a/citation/src/lib.rs#L20-L26

It's basically the auto-cite/CSL idea, but with two variants.

**Comment by denismaier** [comment]
One thing to think about: the current citation modes are a bit orthogonal. Author- year might happen in a note (actually quite common in certain disciplines, e.g. archeology). On the other hand, author title citations might appear in text (e.g. MLA). So, I think default position and rendering should be independent from each other

**Comment by bdarcus** [comment]
I'm contemplating a bit more what goes together, and what should remain separate, in #87.

I hadn't actually gotten to considering citation position yet, but does what you suggest mean something like this would be appropriate?

```yaml
citationPosition: footnote
processing: author-date # in #87, processing would cover sorting, grouping and disambiguation
```

**Comment by denismaier** [comment]
Yes, I think that would be more appropriate. Would perhaps be better to call it `defaultCitationPosition`, or so.

**Comment by bdarcus** [comment]
> Would perhaps be better to call it `defaultCitationPosition`, or perhaps something like something like `defaultCitationTemplate`.

You're thinking so a user could mix-and-match in a document?

If yes, I'd imagine the processing would get a fair bit more complicated?

But certainly best to avoid unstated/acknowledge assumptions.

Also, isn't `template` and `position` orthogonal?

**Comment by denismaier** [comment]
Well, I just thinking about this in terms of how biblatex does it: define a bunch of citation commands, and set one as the default.

```yaml
options: 
  processing: author-date # this sets sorting and grouping for author-date
  defaultCitationTemplate: parens # but this may also be the a task for the calling program.
...
citation:
  templates:
    - plain
      - contributor: author
        form: short
    - parens
      - contributor: author
        form: short
    - narrative
      - contributor: author
        form: short
```

**Comment by bdarcus** [comment]
I'm toying now with extending some of the design tweaks, so one could do something like this:

```yaml
title: ABC journal
processing: author-date # preset processing
dates: long # preset dates
contributors: long # preset contributors
titles: apa # preset titles
citation:
  template:
    - contributor: author
 ```
