### ISSUE TITLE
I'm toying now with extending some of the design tweaks, so one could do something like this:

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csln#89]
I'm toying now with extending some of the design tweaks, so one could do something like this:

```yaml
title: ABC journal
processing: author-date # preset processing
dates: long # preset dates
contributors: long # preset contributors
titles: apa # preset titles
citation:
  template:
    - contributor: author
 ```

_Originally posted by @bdarcus in https://github.com/bdarcus/csln/issues/49#issuecomment-1604980433_

**Comment by bdarcus** [comment]
@denismaier - as followup to the ping, this is what I'm experimenting with, just with YAML (no code ATM).

```yaml
---
info:
  title: Chicago 17, author-date
processing: author-date-chicago 
titles:
  monograph:
    italics: true
  component:
    quoted: true
contributors:
  role: verb-long
  form:
    citation: short
    bibliography: full-chicago
substitute:
  role: short
  template:
    - editor
    - title
    - translator
```
