### ISSUE TITLE
Input model tweaks

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csln#90]
1. allow string for `sub` title, don't require `full`
2. hook up publisher as contributor, with "name" and "location"; probably requires changing `SimpleName` from `String` to a struct
3. WTD with URL, access date? Maybe:

```yaml
access:
  url: ...
  date: 2020-10-11
```

... which could also be used for archival documents and such?
