### ISSUE TITLE
Add support for parent refid

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/csln#97]
I didn't initially know how to do this, but one possibility is to somehow access the parent via the `Processor.bibliography` field hash map.

**Comment by denismaier** [comment]
Hmm, what about using a pre-processing step? Say, you have this initial input data:

```yaml
doeArticle:
  author: 
    family: Doe
    given: John
  title: A very important book chapter
  pages: 1-20
  container:
    id: editedVolume

editedVolume:
  title: A edited volume
  editor:
    family: Smith
    given: Jane
  publisher:
    name: Whatever Press
    location: Wherever
```

Then, after a preprocessing step the data from the parent entry will be merged with the contained entry so that all data is in fact inline:

```yaml
doeArticle:
  author: 
    family: Doe
    given: John
  title: A very important book chapter
  pages: 1-20
  container:
    id: editedVolume
    title: A edited volume
    editor:
      family: Smith
      given: Jane
    publisher:
      name: Whatever Press
      location: Wherever

editedVolume:
  title: A edited volume
  editor:
    family: Smith
    given: Jane
  publisher:
    name: Whatever Press
    location: Wherever
```

Now, you should be able to just use the methods attached to `InputReference`. Right?

With `biber` you can define some very sophisticated preprocessing steps and inheritance rules.

You could go even further and extract arbitrary pieces of data and make them reusable:

```yaml
doe:
  author: 
    family: Doe
    given: John

smith:
  editor:
    family: Smith
    given: Jane

whatever:
  publisher:
    name: Whatever Press
    location: Wherever
  
doeArticle:
  author:
    id: doe 
  title: A very important book chapter
  pages: 1-20
  container:
    id: editedVolume

editedVolume:
  title: A edited volume
  editor:
    id: smith
  publisher:
    id: whatever
```
